model_list:
  - model_name: gpt-oss:120b-cloud
    litellm_params:
      model: openai/gpt-oss:120b-cloud
      api_base: "os.environ/LITELLM_BASE_URL"
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-oss:20b
    litellm_params:
      model: openai/gpt-oss:20b
      api_base: "os.environ/LITELLM_BASE_URL"
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gpt-oss:20b-cloud
    litellm_params:
      model: openai/gpt-oss:20b-cloud
      api_base: "os.environ/LITELLM_BASE_URL"
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: gemma4:31b-cloud
    litellm_params:
      model: openai/gemma4:31b-cloud
      api_base: "os.environ/LITELLM_BASE_URL"
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: qwen2.5-coder:32b
    litellm_params:
      model: openai/qwen2.5-coder:32b
      api_base: "os.environ/LITELLM_BASE_URL"
      api_key: "os.environ/OPENAI_API_KEY"
  - model_name: qwen3-coder-next
    litellm_params:
      model: openai/qwen3-coder-next
      api_base: "os.environ/LITELLM_BASE_URL"
      api_key: "os.environ/OPENAI_API_KEY"
