/**
 * Constants for TanStack Query Keys
 */
export const QUERY_KEYS = {
  ADMIN: {
    SKILLS: "skills",
    RECENT_UPLOADS: "recent-uploads",
    PROMPTS: "prompts",
    LOCATIONS: "locations",
    STAGES: "stages",
    JOB_PRIORITIES: "job-priorities",
    POSITIONS: "positions",
    CRITERIA: "criteria",
    DEPARTMENTS: "departments",
    AUDIT_LOGS: "audit-logs",
    USERS: "users",
    ROLES: "roles",
    PERMISSIONS: "permissions",
    ASSOCIATES: "associates",
    ASSOCIATE_DETAIL: "associate",
    GUIDELINES: "guidelines",
    GUIDELINE_DETAIL: "guideline",
    DASHBOARD_DATA: "adminDashboardData",
    CLEAR_CACHE: "adminCache",
  },
  CANDIDATES: {
    SEARCH: "candidateSearch",
    JOB_STAGES: "jobStages",
    EVALUATION: "evaluation",
    EVALUATION_HISTORY: "evaluationHistory",
    TRANSCRIPTS: "candidateTranscripts",
    HR_DECISION_HISTORY: "hrDecisionHistory",
    DETAILS: "candidateDetails",
    TIMELINE: "candidateTimeline",
    TRANSCRIPT: "transcript",
    CROSS_JOB_MATCH: "crossJobMatch",
    SIMILARITY_SCORES: "similarityScores",
    ASSOCIATE_RESULTS: "associateResults"
  },
  JOBS: {
    STATS: "jobStats",
    LIST: "jobs",
    CANDIDATES: "jobCandidates",
    DETAIL: "job",
    ADMIN_LIST: "adminJobs",
    ADMIN_CANDIDATES: "adminCandidates",
    JOB_VERSION: "jobVersion",
    TASK: "jobTask",
    TASK_DOWNLOAD: "candidateTaskDownload",
    TITLES_GROUPED: "jobTitlesGrouped",
    TASK_ASSIGNED: "taskAssigned",
  },
  TASK_PAPERS: {
    LIST: "taskPapersList",
    DETAIL: "taskPaperDetail",
    DOWNLOAD: "taskPaperDownload",
    ASSIGNED: "candidateTaskPaperAssigned",
    TASK_METADATA: "candidateTaskMetadata",
    SKILLS: "jobAndCandidateSkills",
    HISTORY: "candidateTaskPaperHistory",
    ALL_CONTENT: "all-content",
  },
} as const;
