from .analysis import RESUME_JD_ANALYSIS_PROMPT
from .extraction import RESUME_EXTRACTION_EXAMPLES, RESUME_EXTRACTION_PROMPT
from .instructions import JD_INSTRUCTION, RESUME_INSTRUCTION, SKILL_INSTRUCTION
from .evaluation import EVALUATION_SYSTEM_PROMPT, EVALUATION_USER_PROMPT_TEMPLATE
from .enhancer import PROMPT_ENHANCER_SYSTEM_PROMPT, PROMPT_ENHANCER_USER_PROMPT_TEMPLATE

__all__ = [
    "RESUME_JD_ANALYSIS_PROMPT",
    "RESUME_EXTRACTION_EXAMPLES",
    "RESUME_EXTRACTION_PROMPT",
    "JD_INSTRUCTION",
    "RESUME_INSTRUCTION",
    "SKILL_INSTRUCTION",
    "EVALUATION_SYSTEM_PROMPT",
    "EVALUATION_USER_PROMPT_TEMPLATE",
    "PROMPT_ENHANCER_SYSTEM_PROMPT",
    "PROMPT_ENHANCER_USER_PROMPT_TEMPLATE",
]
