from .analysis import RESUME_JD_ANALYSIS_PROMPT
from .extraction import RESUME_EXTRACTION_EXAMPLES, RESUME_EXTRACTION_PROMPT
from .instructions import JD_INSTRUCTION, RESUME_INSTRUCTION, SKILL_INSTRUCTION

__all__ = [
    "RESUME_JD_ANALYSIS_PROMPT",
    "RESUME_EXTRACTION_EXAMPLES",
    "RESUME_EXTRACTION_PROMPT",
    "JD_INSTRUCTION",
    "RESUME_INSTRUCTION",
    "SKILL_INSTRUCTION",
]
